### PR TITLE
Update for libcamera v0.5.1+rpt20250722

### PR DESCRIPTION
**Pull request by dkaumanns**

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -32,6 +32,7 @@ If you get the error `This package works with libcamera version ..., but you hav
 
 | System and Date | libcamera Reported Version | Pip Package Version |
 | --------------- | -------------------------- | ------------------- |
+| Raspberry Pi Bookworm 13/05/2025 | v0.5.1+100-e53bdf1f | 0.1a11 |
```
Comment (will-v-pi) [inline README.md:35]: This date should match the release date in `rpt20250722`
```suggestion
| Raspberry Pi Bookworm 22/07/2025 | v0.5.1+100-e53bdf1f | 0.1a11 |
```

**Comment by dkaumanns** [comment]
Hi @will-v-pi , thank you for your reply. 

I am not sure if a simple version string replacement will suffice for upgrading to `libcamera` 0.5.1 (as it apparently sufficed for some previous `libcamera` version upgrades).

I am trying to compile `pylibcamera` against `libcamera` 0.5.1 like so (per `libcamera` README):

```Dockerfile
RUN uv pip install rpi-libcamera \
    --config-settings setup-args="-Drepository=https://github.com/raspberrypi/libcamera.git" \
    --config-settings setup-args="-Drevision=v0.5.1+rpt20250722" \
    --config-settings setup-args="-Dversion=unknown"  # -> Skip version check. Should result in v0.5.1+100-e53bdf1f.
```

It fails at compiling the `libcamera` 0.5.1 dependency. See full error log below.

I think has something to do with some private headers that were made inaccessible:

```
5.965       "Private headers must not be included in the libcamera API"
5.965          21 | #error "Private headers must not be included in the libcamera
5.965       API"
```

Currently debugging. There may be some deeper changes necessary. Do you have an idea what could be the issue?

Full error log:

```
 > [10/12] RUN uv pip install rpi-libcamera     --config-settings setup-args="-Drepository=https://github.com/raspberrypi/libcamera.git"     --config-settings setup-args="-Drevision=v0.5.1+rpt20250722"     --config-settings setup-args="-Dversion=unknown"  # -> Skip version check. Should result in v0.5.1+100-e53bdf1f.:                         
0.351 Resolved 1 package in 244ms                                                                                                                                           
0.351    Building rpi-libcamera==0.1a10
5.965   × Failed to build `rpi-libcamera==0.1a10`
5.965   ├─▶ The build backend returned an error
5.965   ╰─▶ Call to `mesonpy.build_wheel` failed (exit status: 1)
5.965 
5.965       [stdout]
5.965       + meson setup
5.965       /root/.cache/uv/sdists-v9/pypi/rpi-libcamera/0.1a10/0XRcoyD9g5RQpLl1teMRW/src
5.965       /root/.cache/uv/sdists-v9/pypi/rpi-libcamera/0.1a10/0XRcoyD9g5RQpLl1teMRW/src/.mesonpy-rar0yumd
5.965       -Dbuildtype=release -Db_ndebug=if-release
5.965       -Db_vscrt=md -Drevision=v0.5.0+rpt20250429
5.965       -Drepository=https://github.com/raspberrypi/libcamera.git
5.965       -Dversion=v0.5.0+59-d83ff0a4
5.965       -Drepository=https://github.com/raspberrypi/libcamera.git
5.965       -Drevision=v0.5.1+rpt20250722 -Dversion=unknown
5.965       --native-file=/root/.cache/uv/sdists-v9/pypi/rpi-libcamera/0.1a10/0XRcoyD9g5RQpLl1teMRW/src/.mesonpy-rar0yumd/meson-python-native-file.ini
5.965       The Meson build system
5.965       Version: 1.8.3
5.965       Source dir:
5.965       /root/.cache/uv/sdists-v9/pypi/rpi-libcamera/0.1a10/0XRcoyD9g5RQpLl1teMRW/src
5.965       Build dir:
5.965       /root/.cache/uv/sdists-v9/pypi/rpi-libcamera/0.1a10/0XRcoyD9g5RQpLl1teMRW/src/.mesonpy-rar0yumd
5.965       Build type: native build
5.965       Project name: pylibcamera
5.965       Project version: 0.1.0
5.965       C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian
5.965       12.2.0-14+deb12u1) 12.2.0")
5.965       C linker for the host machine: cc ld.bfd 2.40
5.965       C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Debian
5.965       12.2.0-14+deb12u1) 12.2.0")
5.965       C++ linker for the host machine: c++ ld.bfd 2.40
5.965       Host machine cpu family: aarch64
5.965       Host machine cpu: aarch64
5.965       Message: Cloning from: https://github.com/raspberrypi/libcamera.git,
5.965       revision v0.5.1+rpt20250722
5.965       Message: Version Check Not Done
5.965       Found pkg-config: YES (/usr/bin/pkg-config) 1.8.1
5.965       Run-time dependency libcamera found: YES 0.5.1
5.965       Program ./parser.py found: YES
5.965       (/root/.cache/uv/sdists-v9/pypi/rpi-libcamera/0.1a10/0XRcoyD9g5RQpLl1teMRW/src/libcamera/utils/codegen/ipc/./parser.py)
5.965       Program ./generate.py found: YES
5.965       (/root/.cache/uv/sdists-v9/pypi/rpi-libcamera/0.1a10/0XRcoyD9g5RQpLl1teMRW/src/libcamera/utils/codegen/ipc/./generate.py)
5.965       Program ./extract-docs.py found: YES
5.965       (/root/.cache/uv/sdists-v9/pypi/rpi-libcamera/0.1a10/0XRcoyD9g5RQpLl1teMRW/src/libcamera/utils/codegen/ipc/./extract-docs.py)
5.965       Program python (jinja2, yaml, jinja2, ply) found: YES
5.965       (/root/.cache/uv/builds-v0/.tmp7gcbe7/bin/python) modules: jinja2, yaml,
5.965       jinja2, ply
5.965       Run-time dependency python3 found: YES 3.11
5.965       pybind11-config found: YES
5.965       (/root/.cache/uv/builds-v0/.tmp7gcbe7/bin/pybind11-config) 3.0.0
5.965       Run-time dependency pybind11 found: YES 3.0.0
5.965       Message: Using python version 3.11.13 from
5.965       /root/.cache/uv/builds-v0/.tmp7gcbe7/bin/python
5.965       Run-time dependency python found: YES 3.11
5.965       Build targets in project: 6
5.965 
5.965       pylibcamera 0.1.0
5.965 
5.965         User defined options
5.965           Native files:
5.965       /root/.cache/uv/sdists-v9/pypi/rpi-libcamera/0.1a10/0XRcoyD9g5RQpLl1teMRW/src/.mesonpy-rar0yumd/meson-python-native-file.ini
5.965           b_ndebug    : if-release
5.965           b_vscrt     : md
5.965           buildtype   : release
5.965           repository  : https://github.com/raspberrypi/libcamera.git
5.965           revision    : v0.5.1+rpt20250722
5.965           version     : unknown
5.965 
5.965       Found ninja-1.11.1.git.kitware.jobserver-1 at
5.965       /root/.cache/uv/builds-v0/.tmp7gcbe7/bin/ninja
5.965       + /root/.cache/uv/builds-v0/.tmp7gcbe7/bin/ninja
5.965       [1/25] Compiling C++ object
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_camera_manager.cpp.o
5.965       FAILED: libcamera/src/py/libcamera/_libcamera.so.p/py_camera_manager.cpp.o
5.965       c++ -Ilibcamera/src/py/libcamera/_libcamera.so.p
5.965       -Ilibcamera/src/py/libcamera -I../libcamera/src/py/libcamera
5.965       -I/usr/include/libcamera -I/usr/local/include/python3.11
5.965       -I/root/.cache/uv/builds-v0/.tmp7gcbe7/lib/python3.11/site-packages/pybind11/include
5.965       -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall
5.965       -Winvalid-pch -Wextra -Werror -std=c++17 -O3 -fPIC -fvisibility=hidden
5.965       -Wno-shadow -DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT -MD -MQ
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_camera_manager.cpp.o -MF
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_camera_manager.cpp.o.d -o
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_camera_manager.cpp.o -c
5.965       ../libcamera/src/py/libcamera/py_camera_manager.cpp
5.965       In file included from
5.965       ../libcamera/src/py/libcamera/py_camera_manager.cpp:6:
5.965       ../libcamera/src/py/libcamera/py_camera_manager.h:8:10: fatal error:
5.965       libcamera/base/mutex.h: No such file or directory
5.965           8 | #include <libcamera/base/mutex.h>
5.965             |          ^~~~~~~~~~~~~~~~~~~~~~~~
5.965       compilation terminated.
5.965       [2/25] Compiling C++ object
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_main.cpp.o
5.965       FAILED: libcamera/src/py/libcamera/_libcamera.so.p/py_main.cpp.o
5.965       c++ -Ilibcamera/src/py/libcamera/_libcamera.so.p
5.965       -Ilibcamera/src/py/libcamera -I../libcamera/src/py/libcamera
5.965       -I/usr/include/libcamera -I/usr/local/include/python3.11
5.965       -I/root/.cache/uv/builds-v0/.tmp7gcbe7/lib/python3.11/site-packages/pybind11/include
5.965       -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall
5.965       -Winvalid-pch -Wextra -Werror -std=c++17 -O3 -fPIC -fvisibility=hidden
5.965       -Wno-shadow -DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT -MD -MQ
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_main.cpp.o -MF
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_main.cpp.o.d -o
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_main.cpp.o -c
5.965       ../libcamera/src/py/libcamera/py_main.cpp
5.965       In file included from ../libcamera/src/py/libcamera/py_main.cpp:8:
5.965       ../libcamera/src/py/libcamera/py_main.h:8:10: fatal error:
5.965       libcamera/base/log.h: No such file or directory
5.965           8 | #include <libcamera/base/log.h>
5.965             |          ^~~~~~~~~~~~~~~~~~~~~~
5.965       compilation terminated.
5.965       [3/25] Generating libcamera/src/py/libcamera/py_gen_formats with a
5.965       custom command
5.965       [4/25] Compiling C++ object
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_enums.cpp.o
5.965       FAILED: libcamera/src/py/libcamera/_libcamera.so.p/py_enums.cpp.o
5.965       c++ -Ilibcamera/src/py/libcamera/_libcamera.so.p
5.965       -Ilibcamera/src/py/libcamera -I../libcamera/src/py/libcamera
5.965       -I/usr/include/libcamera -I/usr/local/include/python3.11
5.965       -I/root/.cache/uv/builds-v0/.tmp7gcbe7/lib/python3.11/site-packages/pybind11/include
5.965       -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall
5.965       -Winvalid-pch -Wextra -Werror -std=c++17 -O3 -fPIC -fvisibility=hidden
5.965       -Wno-shadow -DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT -MD -MQ
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_enums.cpp.o -MF
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_enums.cpp.o.d -o
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_enums.cpp.o -c
5.965       ../libcamera/src/py/libcamera/py_enums.cpp
5.965       In file included from ../libcamera/src/py/libcamera/py_enums.cpp:12:
5.965       ../libcamera/src/py/libcamera/py_main.h:8:10: fatal error:
5.965       libcamera/base/log.h: No such file or directory
5.965           8 | #include <libcamera/base/log.h>
5.965             |          ^~~~~~~~~~~~~~~~~~~~~~
5.965       compilation terminated.
5.965       [5/25] Compiling C++ object
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_color_space.cpp.o
5.965       FAILED: libcamera/src/py/libcamera/_libcamera.so.p/py_color_space.cpp.o
5.965       c++ -Ilibcamera/src/py/libcamera/_libcamera.so.p
5.965       -Ilibcamera/src/py/libcamera -I../libcamera/src/py/libcamera
5.965       -I/usr/include/libcamera -I/usr/local/include/python3.11
5.965       -I/root/.cache/uv/builds-v0/.tmp7gcbe7/lib/python3.11/site-packages/pybind11/include
5.965       -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall
5.965       -Winvalid-pch -Wextra -Werror -std=c++17 -O3 -fPIC -fvisibility=hidden
5.965       -Wno-shadow -DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT -MD -MQ
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_color_space.cpp.o -MF
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_color_space.cpp.o.d -o
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_color_space.cpp.o -c
5.965       ../libcamera/src/py/libcamera/py_color_space.cpp
5.965       In file included from
5.965       ../libcamera/src/py/libcamera/py_color_space.cpp:15:
5.965       ../libcamera/src/py/libcamera/py_main.h:8:10: fatal error:
5.965       libcamera/base/log.h: No such file or directory
5.965           8 | #include <libcamera/base/log.h>
5.965             |          ^~~~~~~~~~~~~~~~~~~~~~
5.965       compilation terminated.
5.965       [6/25] Compiling C++ object
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_transform.cpp.o
5.965       FAILED: libcamera/src/py/libcamera/_libcamera.so.p/py_transform.cpp.o
5.965       c++ -Ilibcamera/src/py/libcamera/_libcamera.so.p
5.965       -Ilibcamera/src/py/libcamera -I../libcamera/src/py/libcamera
5.965       -I/usr/include/libcamera -I/usr/local/include/python3.11
5.965       -I/root/.cache/uv/builds-v0/.tmp7gcbe7/lib/python3.11/site-packages/pybind11/include
5.965       -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall
5.965       -Winvalid-pch -Wextra -Werror -std=c++17 -O3 -fPIC -fvisibility=hidden
5.965       -Wno-shadow -DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT -MD -MQ
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_transform.cpp.o -MF
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_transform.cpp.o.d -o
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_transform.cpp.o -c
5.965       ../libcamera/src/py/libcamera/py_transform.cpp
5.965       In file included from ../libcamera/src/py/libcamera/py_transform.cpp:15:
5.965       ../libcamera/src/py/libcamera/py_main.h:8:10: fatal error:
5.965       libcamera/base/log.h: No such file or directory
5.965           8 | #include <libcamera/base/log.h>
5.965             |          ^~~~~~~~~~~~~~~~~~~~~~
5.965       compilation terminated.
5.965       [7/25] Generating libcamera/src/py/libcamera/py_gen_properties with a
5.965       custom command (wrapped by meson to set env)
5.965       [8/25] Compiling C++ object
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_geometry.cpp.o
5.965       FAILED: libcamera/src/py/libcamera/_libcamera.so.p/py_geometry.cpp.o
5.965       c++ -Ilibcamera/src/py/libcamera/_libcamera.so.p
5.965       -Ilibcamera/src/py/libcamera -I../libcamera/src/py/libcamera
5.965       -I/usr/include/libcamera -I/usr/local/include/python3.11
5.965       -I/root/.cache/uv/builds-v0/.tmp7gcbe7/lib/python3.11/site-packages/pybind11/include
5.965       -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall
5.965       -Winvalid-pch -Wextra -Werror -std=c++17 -O3 -fPIC -fvisibility=hidden
5.965       -Wno-shadow -DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT -MD -MQ
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_geometry.cpp.o -MF
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_geometry.cpp.o.d -o
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_geometry.cpp.o -c
5.965       ../libcamera/src/py/libcamera/py_geometry.cpp
5.965       In file included from ../libcamera/src/py/libcamera/py_geometry.cpp:17:
5.965       ../libcamera/src/py/libcamera/py_main.h:8:10: fatal error:
5.965       libcamera/base/log.h: No such file or directory
5.965           8 | #include <libcamera/base/log.h>
5.965             |          ^~~~~~~~~~~~~~~~~~~~~~
5.965       compilation terminated.
5.965       [9/25] Generating libcamera/src/py/libcamera/py_gen_controls with a
5.965       custom command (wrapped by meson to set env)
5.965       [10/25] Compiling C++ object
5.965       _libcamera.cpython-311-aarch64-linux-gnu.so.p/libcamera_src_py_libcamera_py_camera_manager.cpp.o
5.965       FAILED:
5.965       _libcamera.cpython-311-aarch64-linux-gnu.so.p/libcamera_src_py_libcamera_py_camera_manager.cpp.o
5.965       c++ -I_libcamera.cpython-311-aarch64-linux-gnu.so.p -I.
5.965       -I.. -I../libcamera/include -Ilibcamera/src/py/libcamera
5.965       -I../libcamera/src/py/libcamera
5.965       -I/usr/include/libcamera -I/usr/local/include/python3.11
5.965       -I/root/.cache/uv/builds-v0/.tmp7gcbe7/lib/python3.11/site-packages/pybind11/include
5.965       -fvisibility=hidden -fvisibility-inlines-hidden
5.965       -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall
5.965       -Winvalid-pch -Wextra -Werror -std=c++17 -O3 -fPIC -fvisibility=hidden
5.965       -Wno-shadow -DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT -MD -MQ
5.965       _libcamera.cpython-311-aarch64-linux-gnu.so.p/libcamera_src_py_libcamera_py_camera_manager.cpp.o
5.965       -MF
5.965       _libcamera.cpython-311-aarch64-linux-gnu.so.p/libcamera_src_py_libcamera_py_camera_manager.cpp.o.d
5.965       -o
5.965       _libcamera.cpython-311-aarch64-linux-gnu.so.p/libcamera_src_py_libcamera_py_camera_manager.cpp.o
5.965       -c ../libcamera/src/py/libcamera/py_camera_manager.cpp
5.965       In file included from ../libcamera/include/libcamera/base/mutex.h:13,
5.965                        from
5.965       ../libcamera/src/py/libcamera/py_camera_manager.h:8,
5.965                        from
5.965       ../libcamera/src/py/libcamera/py_camera_manager.cpp:6:
5.965       ../libcamera/include/libcamera/base/private.h:21:2: error: #error
5.965       "Private headers must not be included in the libcamera API"
5.965          21 | #error "Private headers must not be included in the libcamera
5.965       API"
5.965             |  ^~~~~
5.965       In file included from
5.965       ../libcamera/include/libcamera/base/thread_annotations.h:10,
5.965                        from ../libcamera/include/libcamera/base/mutex.h:15:
5.965       ../libcamera/include/libcamera/base/private.h:21:2: error: #error
5.965       "Private headers must not be included in the libcamera API"
5.965          21 | #error "Private headers must not be included in the libcamera
5.965       API"
5.965             |  ^~~~~
5.965       In file included from ../libcamera/include/libcamera/base/log.h:14,
5.965                        from ../libcamera/src/py/libcamera/py_main.h:8,
5.965                        from
5.965       ../libcamera/src/py/libcamera/py_camera_manager.cpp:15:
5.965       ../libcamera/include/libcamera/base/private.h:21:2: error: #error
5.965       "Private headers must not be included in the libcamera API"
5.965          21 | #error "Private headers must not be included in the libcamera
5.965       API"
5.965             |  ^~~~~
5.965       In file included from ../libcamera/include/libcamera/base/utils.h:24,
5.965                        from ../libcamera/include/libcamera/base/log.h:17:
5.965       ../libcamera/include/libcamera/base/private.h:21:2: error: #error
5.965       "Private headers must not be included in the libcamera API"
5.965          21 | #error "Private headers must not be included in the libcamera
5.965       API"
5.965             |  ^~~~~
5.965       [11/25] Compiling C++ object
5.965       _libcamera.cpython-311-aarch64-linux-gnu.so.p/libcamera_src_py_libcamera_py_color_space.cpp.o
5.965       FAILED:
5.965       _libcamera.cpython-311-aarch64-linux-gnu.so.p/libcamera_src_py_libcamera_py_color_space.cpp.o
5.965       c++ -I_libcamera.cpython-311-aarch64-linux-gnu.so.p -I.
5.965       -I.. -I../libcamera/include -Ilibcamera/src/py/libcamera
5.965       -I../libcamera/src/py/libcamera
5.965       -I/usr/include/libcamera -I/usr/local/include/python3.11
5.965       -I/root/.cache/uv/builds-v0/.tmp7gcbe7/lib/python3.11/site-packages/pybind11/include
5.965       -fvisibility=hidden -fvisibility-inlines-hidden
5.965       -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall
5.965       -Winvalid-pch -Wextra -Werror -std=c++17 -O3 -fPIC -fvisibility=hidden
5.965       -Wno-shadow -DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT -MD -MQ
5.965       _libcamera.cpython-311-aarch64-linux-gnu.so.p/libcamera_src_py_libcamera_py_color_space.cpp.o
5.965       -MF
5.965       _libcamera.cpython-311-aarch64-linux-gnu.so.p/libcamera_src_py_libcamera_py_color_space.cpp.o.d
5.965       -o
5.965       _libcamera.cpython-311-aarch64-linux-gnu.so.p/libcamera_src_py_libcamera_py_color_space.cpp.o
5.965       -c ../libcamera/src/py/libcamera/py_color_space.cpp
5.965       In file included from ../libcamera/include/libcamera/base/log.h:14,
5.965                        from ../libcamera/src/py/libcamera/py_main.h:8,
5.965                        from
5.965       ../libcamera/src/py/libcamera/py_color_space.cpp:15:
5.965       ../libcamera/include/libcamera/base/private.h:21:2: error: #error
5.965       "Private headers must not be included in the libcamera API"
5.965          21 | #error "Private headers must not be included in the libcamera
5.965       API"
5.965             |  ^~~~~
5.965       In file included from ../libcamera/include/libcamera/base/utils.h:24,
5.965                        from ../libcamera/include/libcamera/base/log.h:17:
5.965       ../libcamera/include/libcamera/base/private.h:21:2: error: #error
5.965       "Private headers must not be included in the libcamera API"
5.965          21 | #error "Private headers must not be included in the libcamera
5.965       API"
5.965             |  ^~~~~
5.965       [12/25] Compiling C++ object
5.965       libcamera/src/py/libcamera/_libcamera.so.p/py_helpers.cpp.o
5.965       ninja: build stopped: subcommand failed.
5.965 
5.965       hint: This usually indicates a problem with the package or the build
5.965       environment.
------
Dockerfile:69
--------------------
  68 |     # In theory, the following should allow pylibcamera to work with libcamera 0.5.1.
  69 | >>> RUN uv pip install rpi-libcamera \
  70 | >>>     --config-settings setup-args="-Drepository=https://github.com/raspberrypi/libcamera.git" \
  71 | >>>     --config-settings setup-args="-Drevision=v0.5.1+rpt20250722" \
  72 | >>>     --config-settings setup-args="-Dversion=unknown"  # -> Skip version check. Should result in v0.5.1+100-e53bdf1f.
  73 |     
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c uv pip install rpi-libcamera     --config-settings setup-args=\"-Drepository=https://github.com/raspberrypi/libcamera.git\"     --config-settings setup-args=\"-Drevision=v0.5.1+rpt20250722\"     --config-settings setup-args=\"-Dversion=unknown\"  # -> Skip version check. Should result in v0.5.1+100-e53bdf1f." did not complete successfully: exit code: 1
make: *** [test-build-cognicam-core] Error 1
```
